### ISSUE TITLE
Android 8.0 not supported

### ISSUE THREAD

**Issue by insanepure** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#12]
Not working with android 8.0.

Error is something like:
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgument
Exception: Don't know how to process version 5
at AndroidBackup.extractAsTar(AndroidBackup.java:232)
at Main.main(Main.java:40)
Caused by: java.lang.IllegalArgumentException: Don't know how to process version
5
at AndroidBackup.extractAsTar(AndroidBackup.java:72)

**Comment by Antarikshruler** [comment]
antariksh@antariksh-HP-Pavilion-Notebook:~/Downloads/WhatsApp-Key-DB-Extractor-master$ sudo ./WhatsAppKeyDBExtract.sh

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================


Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *
./WhatsAppKeyDBExtract.sh: line 57: [: -eq: unary operator expected

Found legacy WhatsApp 2.11.431 in local folder

WhatsApp 2.18.199 installed

Backing up WhatsApp 2.18.199
6652 KB/s (41547571 bytes in 6.098s)
Backup complete

Removing WhatsApp 2.18.199 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
4057 KB/s (75679 bytes in 0.018s)
Error: Failed to parse APK file: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter: 
antariksh
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
	at org.nick.abe.Main.main(Main.java:128)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
	... 6 more
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Saving whatsapp.cryptkey ...
cp: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory
Saving msgstore.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/msgstore.db': No such file or directory
Saving wa.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/wa.db': No such file or directory
Saving axolotl.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/axolotl.db': No such file or directory
Saving chatsettings.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/chatsettings.db': No such file or directory

Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia
cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

Restoring WhatsApp 2.18.199
6254 KB/s (41547571 bytes in 6.487s)
Success
Restore complete

Cleaning up temporary files ...
rm: cannot remove 'tmp/whatsapp.tar': No such file or directory
Done

Operation complete

Please press Enter to quit...k

**Comment by Antarikshruler** [comment]
Similar error here... plz help...!!!!

**Comment by kevineduardo** [comment]
Same here.

**Comment by fernapo** [comment]
same mistake. i cant access my backup.
rooted my device and lost it all. is there a way to restore old and backup files?
