### ISSUE TITLE
Doesn't work under Android 8.0. Any chance to fix?

### ISSUE THREAD

**Issue by reDDevil77** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#16]
WhatsApp 2.18.92 installed

Found legacy WhatsApp 2.11.431 in local folder

Backing up WhatsApp 2.18.92
2495 KB/s (32461441 bytes in 12.705s)
Backup complete

Removing WhatsApp 2.18.92 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
2782 KB/s (18329558 bytes in 6.432s)
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now
bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...

Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\whatsapp.ab
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\waplen.txt
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\sdpath.txt
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\wapath.txt
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\wapver.txt
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\sdkver.txt

Done

Restoring WhatsApp 2.18.92
3360 KB/s (32461441 bytes in 9.432s)
Success

Restore complete

Removing WhatsApp 2.18.92 temporary apk
Удален файл - E:\Downloads\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\tmp\base.apk

Operation complete

**Comment by Antarikshruler** [comment]
Similar error here. Plz help......

**Comment by Antarikshruler** [comment]
antariksh@antariksh-HP-Pavilion-Notebook:~/Downloads/WhatsApp-Key-DB-Extractor-master$ sudo ./WhatsAppKeyDBExtract.sh

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================


Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *
./WhatsAppKeyDBExtract.sh: line 57: [: -eq: unary operator expected

Found legacy WhatsApp 2.11.431 in local folder

WhatsApp 2.18.199 installed

Backing up WhatsApp 2.18.199
6652 KB/s (41547571 bytes in 6.098s)
Backup complete

Removing WhatsApp 2.18.199 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
4057 KB/s (75679 bytes in 0.018s)
Error: Failed to parse APK file: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter: 
antariksh
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
	at org.nick.abe.Main.main(Main.java:128)
	... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
	... 6 more
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
tar: tmp/whatsapp.tar: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now

Saving whatsapp.cryptkey ...
cp: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory
Saving msgstore.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/msgstore.db': No such file or directory
Saving wa.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/wa.db': No such file or directory
Saving axolotl.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/axolotl.db': No such file or directory
Saving chatsettings.db ...
cp: cannot stat 'tmp/apps/com.whatsapp/db/chatsettings.db': No such file or directory

Pushing cipher key to: /sdcard/WhatsApp/Databases/.nomedia
cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

Restoring WhatsApp 2.18.199
6254 KB/s (41547571 bytes in 6.487s)
Success
Restore complete

Cleaning up temporary files ...
rm: cannot remove 'tmp/whatsapp.tar': No such file or directory
Done

Operation complete

Please press Enter to quit...k

**Comment by Edude** [comment]
Some more info:
before entering the password in terminal, I noticed size tmp/whatsapp.ab 549 bytes, way to small to contain msgstore size 758 kB.
Having read
https://sourceforge.net/p/adbextractor/discussion/general/thread/2c3ede27/
, I hex edited version #5 to #4 in whatsapp.ab, and then entered the password.
I noticed no errormessage, but also no output files.
