### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by schumannd** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#21]
While following the simple instructions I get the following error output:

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.NumberFormatException: For input string: ""
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
	at org.nick.abe.Main.main(Main.java:128)
	... 5 more
Caused by: java.lang.NumberFormatException: For input string: ""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:592)
	at java.lang.Integer.parseInt(Integer.java:615)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:280)
	... 6 more
tar: Error opening archive: Failed to open 'tmp/whatsapp.tar'
tar: Error opening archive: Failed to open 'tmp/whatsapp.tar'
tar: Error opening archive: Failed to open 'tmp/whatsapp.tar'
tar: Error opening archive: Failed to open 'tmp/whatsapp.tar'
tar: Error opening archive: Failed to open 'tmp/whatsapp.tar'

Saving whatsapp.cryptkey ...
cp: tmp/apps/com.whatsapp/f/key: No such file or directory
Saving msgstore.db ...
cp: tmp/apps/com.whatsapp/db/msgstore.db: No such file or directory
Saving wa.db ...
cp: tmp/apps/com.whatsapp/db/wa.db: No such file or directory
Saving axolotl.db ...
cp: tmp/apps/com.whatsapp/db/axolotl.db: No such file or directory
Saving chatsettings.db ...
cp: tmp/apps/com.whatsapp/db/chatsettings.db: No such file or directory

Pushing cipher key to: /storage/emulated/legacy/WhatsApp/Databases/.nomedia
adb: error: cannot stat 'tmp/apps/com.whatsapp/f/key': No such file or directory

```

What is the issue here? Did I skip an important step?

**Comment by schumannd** [comment]
This was caused by my phones adb version being not in sync (too old) with my computers adb version. Ended up solving the issue by using an older version of `adb` on my computer (see https://android.stackexchange.com/questions/83080/adb-backup-creates-0-byte-file-prompts-for-current-backup-password-even-though)

**Comment by FabianK-Dev** [comment]
Hi. Having the same issue here. How did you manage to use an older version of `adb` on your computer?

Thanks in advance for any help!
