### ISSUE TITLE
Exception in thread "main" java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by xCuzImPro** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#24]
Samsung S8+
8.0.0
SEV: 9.0
Kernel: 4.4.111-xxxxx
Update: 1. Oktober 2018

``` powershell

=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.18.327 installed

Found legacy WhatsApp 2.11.431 in local folder

Backing up WhatsApp 2.18.327
4622 KB/s (23838869 bytes in 5.036s)
Backup complete

Removing WhatsApp 2.18.327 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
5029 KB/s (18329558 bytes in 3.558s)
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter: xxxxxxx

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more

D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.18.327
5924 KB/s (23838869 bytes in 3.929s)
Success
Restore complete

Removing WhatsApp 2.18.327 temporary apk


Operation complete

Drücken Sie eine beliebige Taste . . .
```

**Comment by xCuzImPro** [comment]
and blank pw:

``` powerhell


=========================================================================
= This script will extract the WhatsApp Key file and DB on Android 4.0+ =
= You DO NOT need root for this to work but you DO need Java installed. =
= If your WhatsApp version is greater than 2.11.431 (most likely), then =
= a legacy version will be installed temporarily in order to get backup =
= permissions. You will NOT lose ANY data and your current version will =
= be restored at the end of the extraction process so try not to panic. =
= Script by: TripCode (Greets to all who visit: XDA Developers Forums). =
= Thanks to: dragomerlin for ABE and to Abinash Bishoyi for being cool. =
=         ###          Version: v4.7 (12/10/2016)          ###          =
=========================================================================

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 5037 *
* daemon started successfully *

WhatsApp 2.18.327 installed

Found legacy WhatsApp 2.11.431 in local folder

Backing up WhatsApp 2.18.327
3771 KB/s (23838869 bytes in 6.172s)
Backup complete

Removing WhatsApp 2.18.327 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
3894 KB/s (18329558 bytes in 4.596s)
Failure [INSTALL_FAILED_VERSION_DOWNGRADE]
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more

D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
D:\Download\WhatsApp-Key-DB-Extractor-master\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.18.327
4127 KB/s (23838869 bytes in 5.640s)
Success
Restore complete

Removing WhatsApp 2.18.327 temporary apk


Operation complete

Drücken Sie eine beliebige Taste . . .

```

**Comment by adelsonrms** [comment]
having same error

**Comment by gustavomiglesias** [comment]
Can you fix it? i have same problem

**Comment by akanshSirohi** [comment]
Can I have the source code for abe.jar, so I can fix it, because the same is happening with me

**Comment by Rafysama** [comment]
i have the same problem anyone has found a solution since ?
