### ISSUE TITLE
Java Error

### ISSUE THREAD

**Issue by Yannick1712** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#28]
I got the following shown in the command line:

Please connect your Android device with USB Debugging enabled:

* daemon not running. starting it now on port 4036 *
* daemon started successfully *

WhatsApp 2.19.188 2.11.1 installed

Downloading legacy WhatsApp 2.11.431 to local folder

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   251  100   251    0     0    148      0  0:00:01  0:00:01 --:--:--   148

Backing up WhatsApp 2.19.188 2.11.1
5296 KB/s (25670822 bytes in 4.733s)
Backup complete

Removing WhatsApp 2.19.188 2.11.1 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
7 KB/s (251 bytes in 0.031s)
Error: Failed to parse APK file: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
Install complete

Now unlock your device and confirm the backup operation.

Please enter your backup password (leave blank for none) and press Enter: 0210

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:420)
        at org.nick.abe.Main.main(Main.java:128)
        ... 5 more
Caused by: java.lang.IllegalArgumentException: Don't know how to process version 5
        at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:282)
        ... 6 more

C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Cannot open tmp\whatsapp.tar: No such file or directory
C:\Users\XY\Desktop\WhatsApp-Key-DB-Extractor-master\bin\tar.exe: Error is not recoverable: exiting now

Cleaning up temporary files ...
Done

Restoring WhatsApp 2.19.188 2.11.1
4313 KB/s (25670822 bytes in 5.811s)
Success
Restore complete

Removing WhatsApp 2.19.188 2.11.1 temporary apk

Operation complete

Drücken Sie eine beliebige Taste . . .

Can you help? 
I have Android 8.0 and Java Version 8 Update 211 installed.

**Comment by RuaJean** [comment]
Did you get it to work?
