### ISSUE TITLE
Receiving Error Installing legacy WhatsApp 2.11.431

### ISSUE THREAD

**Issue by dheepak** [EliteAndroidApps/WhatsApp-Key-DB-Extractor#34]
Please connect your Android device with USB Debugging enabled:

* daemon not running; starting now at tcp:5037
* daemon started successfully
./WhatsAppKeyDBExtract.sh: line 57: [: -eq: unary operator expected

Found legacy WhatsApp 2.11.431 in local folder

WhatsApp 2.20.206.24 installed

Backing up WhatsApp 2.20.206.24
/data/app/com.whatsapp-owUBh4PC-r9QoLSs48u47Q==/base.apk: 1 file pulled, 0 skipped. 10.4 MB/s (31188619 bytes in 2.849s)
Backup complete

Removing WhatsApp 2.20.206.24 skipping data
Success
Removal complete

Installing legacy WhatsApp 2.11.431
Performing Streamed Install
adb: failed to install tmp/LegacyWhatsApp.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl209896515.tmp/base.apk: AndroidManifest.xml]
Install complete

WARNING: adb backup is deprecated and may be removed in a future release
Now unlock your device and confirm the backup operation...

**Comment by phwi** [comment]
Did you find any solution or does anyone know a solution? I have the exact same problem...  and I already tried dozens of ADB versions (not helping). 

`Installing legacy WhatsApp 2.11.431
Performing Streamed Install
adb: failed to install tmp/LegacyWhatsApp.apk: Failure [INSTALL_PARSE_FAILED_UNEXPECTED_EXCEPTION: Failed to parse /data/app/vmdl209896515.tmp/base.apk: AndroidManifest.xml]
Install complete`

**Comment by ShadyMedic** [comment]
I have a similar problem. But a slightly different error occurs on the same place.
```
Installing legacy WhatsApp 2.11.431
1 KB/s (251 bytes in 0.133s)
Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk

Exception occurred while executing:
java.lang.IllegalArgumentException: Error: Failed to parse APK file: /data/local/tmp/LegacyWhatsApp.apk
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:471)
        at com.android.server.pm.PackageManagerShellCommand.runInstall(PackageManagerShellCommand.java:1060)
        at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:169)
        at android.os.ShellCommand.exec(ShellCommand.java:104)
        at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:26887)
        at android.os.Binder.shellCommand(Binder.java:916)
        at android.os.Binder.onTransact(Binder.java:790)
        at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:5452)
        at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:5044)
        at android.os.Binder.execTransactInternal(Binder.java:1056)
        at android.os.Binder.execTransact(Binder.java:1029)
Caused by: android.content.pm.PackageParser$PackageParserException: Failed to parse /data/local/tmp/LegacyWhatsApp.apk
        at android.content.pm.PackageParser.parseApkLiteInner(PackageParser.java:1680)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1665)
        at com.android.server.pm.PackageManagerShellCommand.setParamsSize(PackageManagerShellCommand.java:464)
        ... 10 more
Install complete
```

**Comment by bogdank0** [comment]
[Friday 02/12/2022, 01:32:13] Reinstalling original WhatsApp.
[Friday 02/12/2022, 01:32:13] Could not install WhatsApp, install by running "restore_whatsapp.py" or manually installing from Play Store.
However if it crashes then you have to clear storage/clear data from "Settings → App Settings → WhatsApp".
[Friday 02/12/2022, 01:32:13]   pkg: /data/local/tmp/WhatsAppbackup.apk

Failure [INSTALL_FAILED_INVALID_URI]



[Friday 02/12/2022, 01:32:13] Our work with device has finished, it is safe to remove it now.


[Friday 02/12/2022, 01:32:13] Found "whatsapp.ab" in "tmp" folder. Continuing... Size: 77126789 bytes.
[Friday 02/12/2022, 01:32:13] Enter a name for this user (default "user").: user
[Friday 02/12/2022, 01:32:13] Enter same password which you entered on device when prompted earlier.: 123456
[Friday 02/12/2022, 01:32:13] Successfully unpacked "tmp/whatsapp.ab" to "tmp/whatsapp.tar". Size: 155164672 bytes.
[Friday 02/12/2022, 01:32:13] Folder "extracted/" already exists.
[Friday 02/12/2022, 01:32:13] Taking out main files in "tmp/" folder temporarily.
[Friday 02/12/2022, 01:32:13] Copied to "extracted/user": axolotl.db
[Friday 02/12/2022, 01:32:13] "encrypted_backup.key" is not present in tarfile, if you have crypt15 backups then visit "https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/issues/94" for more details.
[Friday 02/12/2022, 01:32:13] "password_data.key" is not present in tarfile, if you have crypt15 backups then visit "https://github.com/YuvrajRaghuvanshiS/WhatsApp-Key-Database-Extractor/issues/94" for more details.
[Friday 02/12/2022, 01:32:13] Copied to "extracted/user": chatsettings.db


same problem (((((((

**Comment by ghost** [comment]
There's a more up-to-date fork here: https://github.com/KnugiHK/WhatsApp-Key-DB-Extractor. It still doesn't work, I'm working on a solution on a personal fork and will submit a PR over there once it's done (if everything works out).
**Edit**: actually, I got it into a working state, but the db is in such an old format that is near-useless, and in the process of trial-and-error development of this, I wiped my whatsapp data twice. Since I can't guarantee that my edits are actually safe and the script is not particularly functional, I don't think I'll be pursuing this solution any furthor. If someone wants to deal with further development, I'll leave my fork up at https://github.com/SamuelSwartzberg/WhatsApp-Key-DB-Extractor.

**Comment by samezrp** [comment]
Hi,
I have still the same issue with your fork:
![image](https://user-images.githubusercontent.com/33499054/214791991-bf66f713-ab69-4949-b02e-83911f4fb01d.png)

with original one:
![image](https://user-images.githubusercontent.com/33499054/214792147-2b5e18f4-11ad-47f5-a84e-3d9b11cdb7d1.png)

**Comment by ghost** [comment]
I'm sorry to say that I don't really have the energy to maintain or bugfix my fork. I'm only leaving it up so that others can build off of it or use some of the diffs to the original fork as inspirations for possible bugfixes or improvements. If you're not confident in writing shell scripts and fixing the relevant issues yourself, please don't use my fork.

**Comment by samezrp** [comment]
It is not connected to your work, it looks like there is no way to install old version of WhatsApp on the phone where 2.23.1.76 was installed. Manual install of 2.11.431 also does not work.
My email was not complain, rather information. BR
